version: "3"
services:
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=skins_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:password@database:5432/skins_db
      - SECRET_KEY=234017y0wpu07yq34taqa34g6jna

    ports:
      - 8080:80
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
