# kube config. Can be used with podman play.
# Before starting, build with: podman build . -t valhalla
# this file contains some example configurations containing credentials.
# if you use this in production, remember to change them.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
data:
  POSTGRES_USER: valhalla
  POSTGRES_PASSWORD: password123
  POSTGRES_DB: valhalla

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: valhalla-config
data:
  SECRET_KEY: changeme
  DATABASE_URL: postgresql+asyncpg://valhalla:password123@valhalla-database/valhalla
  PORT: "8080"

---
apiVersion: v1
kind: Pod
metadata:
  name: valhalla
  labels:
    app: valhalla
spec:
  containers:
    - name: database
      image: docker.io/postgres
      envFrom:
        - configMapRef:
            name: postgresql-config
    - name: api
      image: localhost/valhalla
      envFrom:
        - configMapRef:
            name: valhalla-config
      ports:
        - protocol: TCP
          containerPort: 8080
          hostPort: 8080
