[project]
name = "valhalla"
version = "0.3.0"
description = "An alternative skin server for Minecraft supporting metadata and hd textures"
authors = [
    { name = "Matthew Messinger", email = "mattmess1221@gmail.com" },
]
dependencies = [
    "aiofiles<1.0.0,>=0.8.0",
    "Authlib<2.0.0,>=1.0.1",
    "expiringdict<2.0.0,>=1.2.0",
    "fastapi<1.0.0,>=0.81.0",
    "fs<3.0.0,>=2.4.11",
    "fs-s3fs<2.0.0,>=1.1.1",
    "httpx<1.0.0,>=0.23.0",
    "itsdangerous<3.0.0,>=2.1.2",
    "Jinja2<4.0.0,>=3.1.2",
    "Pillow<10.0.0,>=9.2.0",
    "python-dotenv<1.0.0,>=0.20.0",
    "python-jose<4.0.0,>=3.3.0",
    "python-multipart<1.0.0,>=0.0.5",
    "SQLAlchemy<2.0.0,>=1.4.40",
    "SQLAlchemy-Utils<1.0.0,>=0.38.3",
    "uvicorn<1.0.0,>=0.18.2",
]
requires-python = ">=3.10,<4.0"
license = { text = "MIT" }

[project.urls]
repository = "https://github.com/killjoy1221/ValhallaSkinServer"

[project.optional-dependencies]
prod = [
    "asyncpg>=0.26.0",
    "gunicorn<21.0.0,>=20.1.0",
]

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool.pdm]
[tool.pdm.scripts]
dev.cmd = "uvicorn valhalla.app:app --reload"
dev.env = { ENV = "dev", DEBUG = "1" }

[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.1.3",
    "pytest-cov>=4.0.0",
    "async-asgi-testclient>=1.4.11",
]
dev = [
    "pre-commit>=2.20.0",
    "aiosqlite>=0.17.0",
]
lint = [
    "flake8>=5.0.4",
    "black>=22.10.0",
    "isort>=5.10.1",
]

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "--cov --cov-report=xml --cov-report=term"

[tool.coverage]
exclude_lines = [
    "pragma: no cover"
]

[tool.coverage.run]
omit = [
    ".vscode*"
]
