[tool.poetry]
name = "valhalla"
version = "0.1.0"
description = ""
authors = ["Matthew Messinger <mattmess1221@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
request = "^2019.4.13"
requests = "^2.23.0"
flask = "^1.1.2"
expiringdict = "^1.2.0"
pillow = "^7.1.1"
fs = "^2.4.11"
flask-sqlalchemy = "^2.4.1"
flask-restx = "^0.2.0"
flask-httpauth = "^3.3.0"
sqlalchemy-utils = "^0.36.3"
flask-cdn = "^1.5.3"
psycopg2-binary = "^2.8.5"
gunicorn = "^20.0.4"
fs-s3fs = "^1.1.1"
passlib = "^1.7.2"
raygun4py = "^4.3.0"
python-dotenv = "^0.12.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
