[project]
name = "valhalla"
dynamic = ["version"]
description = "An alternative skin server for Minecraft supporting metadata and hd textures"
readme = { file = "README.md", content-type = "text/markdown" }
authors = [
    { name = "Matthew Messinger", email = "mattmess1221@gmail.com" },
]
dependencies = [
    "aiofiles~=22.1",
    "alembic~=1.8",
    "authlib~=1.1",
    "expiringdict~=1.2",
    "fastapi>=0.110.2",
    "fs~=2.4",
    "fs-s3fs~=1.1",
    "httpx~=0.23",
    "itsdangerous~=2.1",
    "pillow~=9.3",
    "python-dotenv~=0.21",
    "python-jose~=3.3",
    "python-multipart~=0.0",
    "sqlalchemy~=1.4",
    "sqlalchemy-utils~=0.38",
    "uvicorn~=0.19",
]
requires-python = ">=3.10,<4.0"
license = { text = "MIT" }

[project.urls]
repository = "https://github.com/killjoy1221/ValhallaSkinServer"

[project.optional-dependencies]
prod = [
    "asyncpg~=0.27",
    "gunicorn~=20.1",
]

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool.pdm]
[tool.pdm.version]
source = "scm"
write_to = "valhalla/__version__.py"
write_template = "__version__ = '{}'"

[tool.pdm.scripts]
dev.cmd = "uvicorn valhalla.app:app --reload"
dev.env = { ENV = "dev", DEBUG = "1" }
cov = "pytest --cov"
lint.composite = ["black valhalla", "isort valhalla"]

[tool.pdm.dev-dependencies]
test = [
    "pytest~=7.2",
    "pytest-cov~=4.0",
    "async-asgi-testclient~=1.4",
    "aiosqlite~=0.17",
]
dev = [
    "pre-commit~=2.20",
    "aiosqlite~=0.17",
]
lint = [
    "ruff>=0.4.1",
]
types = [
    "mypy>=0.982",
    "types-aiofiles>=22.1.0",
    "types-pillow>=9.2.2.2",
    "types-python-jose>=3.3.4",
    "types-passlib>=1.7.7",
]

[tool.pytest.ini_options]
norecursedirs = [
    "__pypackages__"
]

[tool.coverage]
[tool.coverage.report]
fail_under = 80
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if TYPE_CHECKING:",
    "@overload",
    "class .*Protocol"
]

[tool.coverage.run]
omit = [
    ".vscode*",
    "__pypackages__/*",
]

[tool.mypy]
plugins = [
    "pydantic.mypy",
]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "valhalla.crud"
ignore_errors = true

[tool.ruff]
target-version = 'py310'

[tool.ruff.lint]
select = ["F", "E", "W", "B", "SIM"]
