[tool.poetry]
name = "valhalla"
version = "0.2.0"
description = ""
authors = ["Matthew Messinger <mattmess1221@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.1"
Flask = "^2.1.3"
expiringdict = "^1.2.0"
Pillow = "^9.2.0"
fs = "^2.4.11"
Flask-SQLAlchemy = "^2.5.1"
flask-restx = "^0.5.1"
Flask-HTTPAuth = "^4.7.0"
SQLAlchemy-Utils = "^0.38.3"
Flask-CDN = "^1.5.3"
psycopg2-binary = "^2.9.3"
gunicorn = "^20.1.0"
fs-s3fs = "^1.1.1"
passlib = "^1.7.2"
raygun4py = "^4.3.0"
python-dotenv = "^0.20.0"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
isort = "^5.10.1"
flake8 = "^4.0.1"
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.masonry.api"

[tool.isort]
profile = "black"
